name: Setup Fortran

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]


permissions:
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  test:
    name: ${{ matrix.os }}-${{ matrix.toolchain.compiler }}${{ matrix.toolchain.tag }}
    if: github.event.pull_request.draft == false
    runs-on: ${{ matrix.os }}
    env:
      FPM_FFLAGS: ${{ matrix.toolchain.FPM_FFLAGS }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        toolchain:
          # Separate nvidia compilations removed because using up all
          # our CI minutes!  The code now supports OpenMP+OpenACC
          # anyway, so it makes sense to just compile once
          - {compiler: nvidia-hpc, version: '24.5', FPM_FFLAGS: "-mp -acc=multicore"}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: |
          # Frees up space, so can install nvhpc.
          # See https://github.com/orgs/community/discussions/25678 for
          # where suggestion came from
          rm -rf /opt/hostedtoolcache
      - uses: fortran-lang/setup-fortran@v1
        id: setup-fortran
        with:
          compiler: ${{ matrix.toolchain.compiler }}
          version: ${{ matrix.toolchain.version }}
      - run: |
          mpif90 --version
